apiVersion: backstage.io/v1beta3
kind: Template
metadata:
  name: hello-template
  description: A simple template that echoes "Hello"
  tags:
    - example
spec:
  type: service
  parameters:
    - title: Title
      required: true
      description: The title of the service
  steps:
    - id: echo-hello
      action: output
      params:
        message: "Hello, {{ parameters.title }}!"
