apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
metadata:
  name: hello-backstage
  title: Hello Backstage Template
  description: A template to echo "Hello, Backstage!"
spec:
  owner: user@example.com
  type: service
  steps:
    - id: trigger-jenkins
      name: Trigger Jenkins Job
      action: jenkins:job
      input:
        jobName: "test"  # Replace with the actual name of your Jenkins job
        parameters:
          MESSAGE: "{{ parameters.Message }}"
      output:
        resultUrl: "https://acm-poc.directv.com/job/test"  # Link to the Jenkins job
