apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
metadata:
  name: jenkins-hello-template
  description: A template that triggers a Jenkins job to echo a message
  tags:
    - example
    - jenkins
spec:
  type: service
  parameters:
    - title: Message
      required: true
      description: The message to echo in Jenkins
  steps:
    - id: trigger-jenkins
      name: Trigger Jenkins Job
      action: jenkins:job
      input:
        jobName: "test"  # Replace with the actual name of your Jenkins job
        parameters:
          MESSAGE: "{{ parameters.Message }}"
      output:
        resultUrl: "https://acm-poc.directv.com/job/test"  # Link to the Jenkins job
