apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
metadata:
  name: hello-backstage
  title: Hello Backstage Template
  description: A template to echo "Hello, Backstage!"
spec:
  owner: user@example.com
  type: service
  steps:
    - id: trigger-github-action
      name: Trigger GitHub Actions Workflow
      action: github:actions:workflow-dispatch
      input:
        repoUrl: "https://github.com/cp1408/aws-ec2-rhdh-terraform-new2"  # Replace with your actual repo URL
        workflowId: "echo-message.yml"  # Replace with the actual workflow file name
        ref: "main"  # The branch to trigger the action on
        inputs:
          message: "{{ parameters.Message }}"
      output:
        resultUrl: "https://github.com/cp1408/aws-ec2-rhdh-terraform-new2/actions"  # Link to GitHub Actions
